services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - AWS_DEFAULT_REGION=us-east-2
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --ServerApp.token=${JUPYTER_TOKEN}

  mlflow:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow-data:/mlflow
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:////mlflow/mlflow.db --serve-artifacts --artifacts-destination /mlflow/artifacts --default-artifact-root mlflow-artifacts:/
    
  painel:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - AWS_DEFAULT_REGION=us-east-2
    command: streamlit run app/painel.py --server.port=8501 --server.address=0.0.0.0 --server.headless=true --browser.gatherUsageStats=false